In [1]:
import numpy as np

### Задание 1

In [79]:
a =np.array([[1, 2, 3, 3, 1],
     [6, 8, 11, 10, 7]])
a=a.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [51]:
np.mean(a, axis=0)

array([2. , 8.4])

In [52]:
mean_a=np.copy(np.mean(a, axis=0))
mean_a

array([2. , 8.4])

### Задание 2

In [53]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [54]:
a_centered=a-mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [64]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]
a_centered_sp

8.0

In [71]:
a_centered_sp/(a.shape[0]-1)

2.0

### Задание 4**

In [83]:
a.T

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [93]:
kov= np.cov(a.T)
print(kov)
print('Коварация =', kov[0,1])

[[1.  2. ]
 [2.  4.3]]
Коварация = 2.0
